### ISSUE TITLE
[BUG]: kb-cloud-client解析additionalProperties类型与swagger不一致

### ISSUE THREAD

**Issue by 1aal** [apecloud/kb-cloud-client-go#47]
在cloud中，参数的枚举类型字段的定义是
```
    enum:
      description: The value options of the parameter
      type: array
      items:
        type: object
        additionalProperties: true
```
swagger生成的结构体是

![Image](https://github.com/user-attachments/assets/e59a9947-38f7-40b0-bb41-cd9dbb7ca611)

但是在kb-cloud-client库中生成的类型是

![Image](https://github.com/user-attachments/assets/b4f8f901-828b-4294-955e-bcfe1d357d59)
导致了解析失败

**Comment by 1aal** [comment]
```
clusterMetrics:
  type: object
  description: Cluster metrics
  properties:
    value:
      type: array
      items: {}
      nullable: true
    values:
      type: array
      items:
        type: array
        items: {}
        nullable: true
```
定义成这种形式可以保持两个库之间的一致
